name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3

    - name: Deploy to Ubuntu
      run: |
        mkdir -p ~/.ssh
    
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
        ssh-keyscan -H "$HOST_IP" >> ~/.ssh/known_hosts
        ssh -i ~/.ssh/id_rsa "${HOST_NAME}@${HOST_IP}"
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
