name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Ubuntu
      run: |
        mkdir -p ~/.ssh
        touch ~/.ssh/id_rsa
        echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "before connect"
        ssh -v -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 -i ~/.ssh/id_rsa "${HOST_NAME}@${HOST_IP}" << EOF
        echo "hihihiha"
        EOF
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST_IP: ${{ secrets.HOST_IP }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
